In [20]:
from tensorflow.keras.preprocessing import text
import warnings
warnings.filterwarnings('ignore')
from tensorflow import one_hot

In [2]:
sentences=['I am Het',
          'I am Good boy',
          'I am from DDU',
          'City is NVS']

In [25]:
sentences
vocabulary_size=10000

In [26]:
one_hot_array=[text.one_hot(words,vocabulary_size) for words in sentences]

In [27]:
one_hot_array ##it gives on which index in vocabulary our word store

[[7314, 9981, 2191],
 [7314, 9981, 2412, 2857],
 [7314, 9981, 2743, 3520],
 [8780, 5274, 251]]

In [49]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.layers import Embedding
max_len=8

In [50]:
embedded_docs=pad_sequences(one_hot_array,padding='pre',maxlen=max_len)

In [51]:
##feature presentation
dim=10

In [52]:
model=Sequential()
model.add(Embedding(vocabulary_size,
    dim,input_length=max_len))
model.compile('adam','mse')
model.build(input_shape=(None, max_len))


In [53]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)              │ (None, 8, 10)               │         100,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [57]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step


array([[[-0.01915552,  0.02431417,  0.02285096, -0.04949391,
         -0.03558147,  0.0265136 ,  0.0135484 ,  0.0239308 ,
         -0.04474094, -0.0043381 ],
        [-0.01915552,  0.02431417,  0.02285096, -0.04949391,
         -0.03558147,  0.0265136 ,  0.0135484 ,  0.0239308 ,
         -0.04474094, -0.0043381 ],
        [-0.01915552,  0.02431417,  0.02285096, -0.04949391,
         -0.03558147,  0.0265136 ,  0.0135484 ,  0.0239308 ,
         -0.04474094, -0.0043381 ],
        [-0.01915552,  0.02431417,  0.02285096, -0.04949391,
         -0.03558147,  0.0265136 ,  0.0135484 ,  0.0239308 ,
         -0.04474094, -0.0043381 ],
        [-0.01915552,  0.02431417,  0.02285096, -0.04949391,
         -0.03558147,  0.0265136 ,  0.0135484 ,  0.0239308 ,
         -0.04474094, -0.0043381 ],
        [-0.01895397, -0.03417199,  0.01064958,  0.00779666,
         -0.03704884,  0.01296761,  0.03707853,  0.01153783,
          0.00908775,  0.01872543],
        [ 0.00080778,  0.02135768, -0.02261817,  0.0

In [58]:
##so every word of sentence is represent by 10 words of dimension

In [59]:
embedded_docs[0]

array([   0,    0,    0,    0,    0, 7314, 9981, 2191])

In [56]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None

In [65]:
embedded_docs[0].shape

(8,)

In [63]:
import numpy as np

# Reshape embedded_docs[0] to include the batch dimension
single_input = np.expand_dims(embedded_docs[0], axis=0)

In [64]:
single_input.shape

(1, 8)

In [66]:
model.predict(single_input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step


array([[[-0.01915552,  0.02431417,  0.02285096, -0.04949391,
         -0.03558147,  0.0265136 ,  0.0135484 ,  0.0239308 ,
         -0.04474094, -0.0043381 ],
        [-0.01915552,  0.02431417,  0.02285096, -0.04949391,
         -0.03558147,  0.0265136 ,  0.0135484 ,  0.0239308 ,
         -0.04474094, -0.0043381 ],
        [-0.01915552,  0.02431417,  0.02285096, -0.04949391,
         -0.03558147,  0.0265136 ,  0.0135484 ,  0.0239308 ,
         -0.04474094, -0.0043381 ],
        [-0.01915552,  0.02431417,  0.02285096, -0.04949391,
         -0.03558147,  0.0265136 ,  0.0135484 ,  0.0239308 ,
         -0.04474094, -0.0043381 ],
        [-0.01915552,  0.02431417,  0.02285096, -0.04949391,
         -0.03558147,  0.0265136 ,  0.0135484 ,  0.0239308 ,
         -0.04474094, -0.0043381 ],
        [-0.01895397, -0.03417199,  0.01064958,  0.00779666,
         -0.03704884,  0.01296761,  0.03707853,  0.01153783,
          0.00908775,  0.01872543],
        [ 0.00080778,  0.02135768, -0.02261817,  0.0

In [67]:
embedded_docs.shape

(4, 8)